#!/bin/sh

getopts h _ && {
    echo >&2 "Usage: hidden-files (show|hide)"
    echo >&2 "Turns hidden files visibility on/off."
    exit 2
}

case "$1" in
    (show) value=true  ;;
    (hide) value=false ;;
    (*)    exit 2
esac
defaults write com.apple.Finder AppleShowAllFiles -bool $value
killall Finder
