#!/bin/sh

getopts h _ && {
    echo >&2 "Usage: spotlight-indexing (on|off)"
    echo >&2 "Turns Spotlight indexing on/off."
    exit 2
}

case "$1" in
    (on)  action=load   ;;
    (off) action=unload ;;
    (*)   exit 2
esac
sudo launchctl $action -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
