#!/bin/sh

# Extract the audio from a YouTube video.

if getopts h _ || [ $# -ne 1 ]; then
    echo >&2 "Usage: ytdl <URL>"
    exit 2
fi

youtube-dl "${1}" \
	--no-overwrites \
	--extract-audio \
	--audio-format=m4a \
	--audio-quality=0
